function Hd = nyquist(N,L,bw)
%NYQUIST_2 이산시간 필터 객체를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 04-Nov-2023 12:32:58

% Equiripple Nyquist filter designed using the FIRNYQUIST function.

% All frequency values are normalized to 1.
if(~exist('N','var'))
    N=28;
end
if(~exist('L','var'))
    L=4;
end
if(~exist('bw','var'))
    bw=0.2;
end
BW = bw*(L/2);  % Bandwidth
DT = 'Normal';   % Design Type
D  = 0;          % Decay Rate

% Calculate the coefficients using the FIRPM function.
b  = firnyquist(N, L, BW, D, DT);
Hd = dfilt.dffir(b);

% [EOF]
